name: Release Drafter
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        - name: Make class
          run: javac -d . engine/Core.java
          working-directory: ${{ env.working-directory }}
        - name: make manifest
          run: echo "Main-Class:*  engine.Core" > manifest.txt
          working-directory: ${{ env.working-directory }}
        - name: replace manifest.txt
          run: find ./ -name "manifest.txt" -exec sed -i 's/*/ /g' {} \;
          working-directory: ${{ env.working-directory }}
        - name: make jar
          run: jar -cvmf manifest.txt invader.jar */*
          working-directory: ${{ env.working-directory }}
        - name: Commits
            run: |
              git config --local user.email "kjmin622@naver.com"
              git config --local user.name "kjmin622" # 커밋에 포함될 이름
              git add invader.jar
              git commit -m "add: invader"
            working-directory: ${{ env.working-directory }}
        - name: Push
            uses: ad-m/github-push-action@master
            with:
              branch: 'master'
              github_token: ${{ secrets.TOKEN_KK }}
        - uses: release-drafter/release-drafter@v5
        with:
          config-name: main.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_KK }}
